### ISSUE TITLE
Test results of dbtouch

### ISSUE THREAD

**Issue by fakob** [HusakYurii/pixi-additional-events#1]
Hi @HusakYurii 
I have finally gotten around to test your double touch script. Unfortunately I haven't gotten it to work, but it might be my setup or misunderstanding. Your `dbtouch` event is sort of the double click version of pixi's native `tap` event. Is that correct?

This is what I have done. [This sandbox](https://codesandbox.io/s/pixijs-double-tap-and-click-test-w39sq?file=/src/index.js) is console logging the different actions.
I have run this example on a mac and a pc laptop with a touchpad. As expected, their double "touches" are interpreted as double clicks.
I have then run this example on my Android tablet in a Chrome and an Opera browser. There, only pixi's native `tap` event works, but not your `dbtouch` event. Am I doing something wrong?

Btw, I saw that the double click event is called `dblclick` but the double touch event is missing the letter L `dbtouch`. Is that a typo?

**Comment by HusakYurii** [comment]
@fakob Hey! thank you very much for testing the feature!
Let me answer your questions first:

> _Is that a typo?_

 `dblclick`  is correct , `dbtouch ` has a typo, will fix that

>_Your dbtouch event is sort of the double click version of pixi's native tap event. Is that correct?_

The feature wraps DOM `touchstart`  event (the same way as PIXI does). It collects all  `touchstart` events in [`TouchEventsPool`](https://github.com/HusakYurii/pixi-additional-events/blob/a0eac0f075da4114ab3bd2b8367eced9ae926119/dbtouch.js#L24) and when you **hit** a target , the feature checks some params [here](https://github.com/HusakYurii/pixi-additional-events/blob/a0eac0f075da4114ab3bd2b8367eced9ae926119/dbtouch.js#L83).

>_Am I doing something wrong?_

Your setup is correct. I did the same when was working on the feature. Then by opening the dev tools and setting the screen to Device Mode (Ctrl + Shift + M) I tested the touch events.

I used your example and debugged it in the console. The issue is that the event does not **hit** a target (will investigate), because while [processing the event ](https://github.com/HusakYurii/pixi-additional-events/blob/a0eac0f075da4114ab3bd2b8367eced9ae926119/dbtouch.js#L185) `this.lastObjectRendered` is undefined, but it should be the rectangle

**Comment by HusakYurii** [comment]
@fakob 
Have found the issue. Already fixed it!
Could you please test it one more time?
Just in case, maybe it will be handy, this is the [ draft I tested](https://codepen.io/Yurii_Husak/pen/xxVBYWy)

**Comment by fakob** [comment]
@HusakYurii 
Tested it again. Your fix worked. Perfect, thanks.

**Comment by HusakYurii** [comment]
@fakob nice to hear that!
Thank you for helping me, very appreciate that!
